# @package _global_
alg:
  name: a2c
  model:
    actor_hiddens:
      - 128
      - 128
    critic_hiddens:
      - 128
      - 128
    parameter_sharing: True
    recurrent: False
    layernorm: True # layernorm after each hidden layer
    device: cpu

  greedy_evaluation: false

  lr: 5e-4
  tau: 0.01
  max_grad_norm: 0.0
  entropy_coef: 0.001
  gae_lambda: 1
  gamma: 0.99
  n_steps: 10
