# @package _global_
alg:
  name: a2c_gnn
  model:
    actor_hiddens:
      - 128
      - 128
    critic_hiddens:
      - 128
      - 128
    encoder_dim: 128
    gnn_iterations: 1
    parameter_sharing: True
    recurrent: False
    layernorm: True # layernorm after each hidden layer
    device: cpu
    # gnn_version: gat
    gnn_version: self_attention
    gnn_n_heads: 1
    gnn_is_concat: False
    gnn_dropout:  0.6
    gnn_leaky_relu_negative_slope: 0.2
    gnn_share_weights: False
    gnn_residual_connections: True

  greedy_evaluation: false

  lr: 5e-4
  tau: 0.01
  max_grad_norm: 0.0
  entropy_coef: 0.001
  gae_lambda: 1
  gamma: 0.99
  n_steps: 10
