# @package _global_
env:
  name:
    - pz-mpe-simple-tag-v1

  wrappers:
    - RecordEpisodeStatistics
    - SquashDones
    - AgentOneHotIdWrapper

training:
  num_env_steps: 5000000
  log_interval:  10000
  save_interval: null
  eval_interval: 100000