# @package _global_
env:
  name:
    - pz-mpe-simple-tag-v1
  
  arguments:
    num_adversaries: 3
    num_good: 2
    num_obstacles: 2
    max_frames: 25
    prey_max_speed: 0
    po_distance: 1

  wrappers:
    - RecordEpisodeStatistics
    - SquashDones
    - AgentOneHotIdWrapper

training:
  num_env_steps: 2000000
  update_frequency: 100
  log_interval:  10000
  save_interval: null
  eval_interval: 100000
  logger: wandb