seed: null

# configuration details for training
training:
  num_env_steps: 10000000
  log_interval: 10000
  save_interval: 2000000
  eval_interval: 100000
  episodes_per_eval: 10

# environment to use for training
env:
  name: ??? # needs to be specified for training
  dummy_vecenv: false
  parallel_envs: 4
  max_ep_length: null
  arguments: {}
  fixed_arguments: {}
  wrappers:
    - RecordEpisodeStatistics
    - SquashDones

alg:
  load_run_id: null
  load_step: null
  gamma: 0.99
  standardise_rewards: false

exp_name: null
